Mistakes Correction 2.0.
NoNamedUser/restapi pull request #5
Opened 2019-07-04 11:50 UTC by NoNamedUser

2019-07-09 15:53 UTC, PavelAndryushenko requested changes
В целом, все неплохо, проект развивается, становится лучше но есть ряд ошибок, которые необходимо исправить, они в комментариях.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/MainExceptionHandler.java
> +}
Здесь не хватает обработчика непредвиденного исключения, которое не подпадает ни под одно из описанных - такая ситуация тоже может быть и ее нужно предусмотреть.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/ArgumentExceptionHandler.java
> +public class ArgumentExceptionHandler {
А почему для этого исключения создан отдельный ControllerAdvice? Я предлагаю объединить обработчики всех исключений в одном ControllerAdvice.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/ArgumentExceptionHandler.java
> +        String field = fieldError.getField();
Я так понимаю, что field у нас не используется нигде в методе? Тогда его нужно убрать.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/ProductController.java
> +    private ProductService productService;
productService должен инициализироваться ровно один раз, следовательно, его нужно сделать final.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/ProductController.java
> +    public ResponseEntity<ResponseEntityDto> getProductById(@PathVariable long id) {
Здесь у всех методов, которые потенциально могут сгенерировать проверяемое исключение, нужно добавить эти исключения в блок throws.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/ProductDto.java
> +    private Long id;
DTO всегда должен быть неизменяемым, поэтому, все свойства должны быть final.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/ProductDto.java
> +    public ProductDto() {
Зачем нужен такой конструктор, если у нас нет возможности изменять значения свойств извне?

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/ResponseEntityDto.java
> +    private List<Product> responseBodies;
У нас же не всегда будет отдаваться список продуктов - в половине случаев мы будем отдавать один продукт, здесь, получается, такой возможности нет, только список?

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/ResponseEntityDto.java
> +    public void setResponseBodies(List<Product> responseBodies) {
DTO должен быть неизменяемым, у него не должно быть сеттеров.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/exception/DataCheckingFailedException.java
> + * Data
Такие комментарии не информативные, их не должно быть.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/repository/ProductRepository.java
> +    List<Product> findProductById(long id);
Чем этот метод отличается от getProductById? ID - это первичный ключ, по нему мы всегда будем находить не более 1 продукта.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/repository/ProductRepository.java
> +    List<Product> findProductById(long id);
А качестве параметров методов бинов лучше передавать классы-обертки, а не примитивы.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/repository/ProductRepository.java
>      ArrayList<Product> findProductByNameAndType(String name, String type);
Нужно повысить уровень абстракции - List.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/DataCheckingService.java
> +    boolean checkExistenceOfProduct(ProductRepository productRepository, Product product);
Здесь репозиторий можно не передавать, а автовайрить прямо в сервис.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/ProductService.java
> +    ResponseEntity<ResponseEntityDto> getAllProducts();
Сервис не должен оперировать с запросами о ответами клиенту, это абстракция уровня контроллеров - он должен возвращать либо Entity, либо DTO.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/ProductService.java
> +    ResponseEntity<ResponseEntityDto> updateProduct(ProductDto productDto);
Необходимо добавить проверяемые исключения в интерфейс методов сервиса.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/DataCheckingServiceImpl.java
> +    public DataCheckingServiceImpl(){}
Тут ничего не внедряется, @Autowired не нужен.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/DataCheckingServiceImpl.java
> +        if(productRepository.findProductByNameAndType(product.getName(), product.getType()).isEmpty()){
Здесь не хватает проверок на NULL для переданных параметров.

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/DataCheckingServiceImpl.java
> +        if(productRepository.findProductByNameAndType(product.getName(), product.getType()).isEmpty()){
Можно сократить - return !productRepository.findProductByNameAndType(product.getName(), product.getType()).isEmpty()

2019-07-09 15:53 UTC, PavelAndryushenko commented on src/main/resources/application.properties
> +flyway.user=username
Это устаревшие свойства - нужно использовать spring.flyway.user и т.д.

2019-07-10 10:01 UTC, NoNamedUser commented on src/main/java/restapi/dto/ResponseEntityDto.java
> +    private List<Product> responseBodies;
В случае запроса GET по id возвращается список с единственным элементом. Этот список универсален во всех случаях: и если один элемент ищем, и если все запрашиваем, и если при фильтрации отобралось n-ное количество продуктов. Иначе нам придется иметь поля и List<Product> и Product, причем одно всегда будет пустым(или разделять на разные ResponseEntity, что на мой взгляд нецелесообразно). А так у нас получается "унифицированный" ответ.

2019-07-25 07:51 UTC, merged