Mistakes Correction 2.1.
NoNamedUser/restapi pull request #6
Opened 2019-07-08 07:41 UTC by NoNamedUser

2019-07-10 07:34 UTC, PavelAndryushenko requested changes
Хорошая доработка, многие ошибки исправлены, код явно улучшается.
Есть ряд моментов, которые нужно будет доработать, и можно будет мерджить в мастер.

2019-07-10 07:34 UTC, PavelAndryushenko commented on build.gradle
> +    compile group: 'org.springframework.boot', name: 'spring-boot-starter', version: '2.1.6.RELEASE'
compile - это устаревшая конфигурация, нужно использовать либо implementation, либо compileOnly.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/KindOfProductController.java
> +    private KindOfProductService kindOfProductService;
Каждый внедряемый ресурс должен быть final.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/KindOfProductDto.java
> +    private long id;
Свойства в DTO не должны быть примитивами, поскольку они инициализируются значениями по умолчанию.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/KindOfProductDto.java
> +    public KindOfProductDto() {
Конструктора по умолчанию у DTO быть не должно, поскольку он должен быть иммутабельным.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/KindOfProductDto.java
> +    public void setId(long id) {
Сеттеров у DTO не должно быть, поскольку он должен быть иммутабельным.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/entity/KindOfProduct.java
> +    @ApiModelProperty(notes = "The database generated kind of product ID")
Можно поспорить об этом, но мне кажется, что сущность не должна напрямую завязываться с API - сущность - это модель, а API - это, скорее, представление, модель на нее завязываться не должна.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/repository/KindOfProductRepository.java
> +    boolean existsById(long id);
В сущности id - это Long, а тут передается примитив - лучше так не делать, а передавать так же Long.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/KindOfProductService.java
> +    ResponseEntity<ResponseEntityDto> createKindOfProduct(KindOfProductDto kindOfProductDto);
Сервис не должен взаимодействовать с запросами и ответами к API - он должен оперировать либо с DTO, либо с сущностями.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/ProductService.java
> +    boolean checkExistenceOfProduct(ProductRepository productRepository, Product product);
Репозиторий должен инжектиться в сервис, а не передаваться в качестве параметра. Сервисы будут вызваться из контроллеров, а у них не должно быть доступа к репозиториям.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/KindOfProductServiceImpl.java
> +    public ResponseEntity<ResponseEntityDto> createKindOfProduct(KindOfProductDto kindOfProductDto){
Тут не хватает проверяемого исключения для ошибки, которая может возникнуть при сохранении.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/KindOfProductServiceImpl.java
> +    private KindOfProductDtoService kindOfProductDtoService;
Все внедряемые ресурсы должны быть final.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/KindOfProductServiceImpl.java
> +     * @return - boolean.
Комментарий в @return совсем не информативный - такие нужно либо удалять, либо конкретизировать.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/ProductServiceImpl.java
> +    private ProductDtoService productDtoService;
Все внедряемые ресурсы должны быть final.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/ProductServiceImpl.java
>              throw new NoSuchProductException();
Это проверяемое исключение, должно быть добавлено в объявление метода.

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/ProductServiceImpl.java
> +    public boolean checkExistenceOfProduct(ProductRepository productRepository, Product product){
Не очень информативное название - лучше назвать его isProductExists - так понятно, что именно мы проверяем

2019-07-10 07:34 UTC, PavelAndryushenko commented on src/main/java/restapi/service/impl/ProductServiceImpl.java
> +        return !productRepository.findProductById(id).isEmpty();
Может ли findProductById вернуть NULL? Если да, то не хватает проверки на NULL.

2019-07-12 12:21 UTC, NoNamedUser commented on src/main/java/restapi/entity/KindOfProduct.java
> +    @ApiModelProperty(notes = "The database generated kind of product ID")
Это просто описание моделей в UI Swagger

2019-07-22 11:18 UTC, PavelAndryushenko requested changes
Все, в целом, хорошо, код заметно улучшился - написал 6 замечаний, они не очень сложно поправляются, после их исправления можно будет мерджить в master.

2019-07-22 11:18 UTC, PavelAndryushenko commented on gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
Этот файл нужно удалить и добавить в .gitignore - он не должен помещаться в репозиторий.

2019-07-22 11:18 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/KindOfProductController.java
> +    @ExceptionHandler(KindOfProductNotExistsException.class)
Обработчики исключений нужно перенести в ControllerAdvice.

2019-07-22 11:18 UTC, PavelAndryushenko commented on src/main/java/restapi/controller/ProductController.java
> +
Обработку исключений нужно убрать в ControllerAdvice.

2019-07-22 11:18 UTC, PavelAndryushenko commented on src/main/java/restapi/dto/ProductDto.java
> +        this.id = null;
Нужен ли этот конструктор по умолчанию, используется ли он? По идее, по умолчанию, до инициализации эти свойства итак равны NULL.

2019-07-22 11:18 UTC, PavelAndryushenko commented on src/main/java/restapi/service/product/impl/ProductServiceImpl.java
> +        return new ResponseEntityDto<>("Product was successfully created", null);
А почему здесь передается NULL? По идее, правильно было бы отдавать созданный продукт. Во всех аналогичных местах - то же самое.

2019-07-22 11:18 UTC, PavelAndryushenko commented on src/main/resources/application.properties
> +spring.jpa.show-sql=false
Лучше пусть показывает SQL - так проще отлаживать и понимать, какие запросы идут в БД )

2019-07-22 11:40 UTC, NoNamedUser commented on src/main/java/restapi/dto/ProductDto.java
> +        this.id = null;
Его требует Jackson. Без него вылетает ошибка: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `restapi.dto.ProductDto` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

2019-07-24 10:23 UTC, PavelAndryushenko approved these changes
Все ок, есть одно замечание, но его можно поправить позже.
Реквест аппрувлю, но мердж сделай сам - там есть конфликты, попробуй их разрешить самостоятельно, если будут трудности, то обращайся, я расскажу, как это лучше сделать.

2019-07-24 10:23 UTC, PavelAndryushenko commented on src/main/java/restapi/service/kindofproduct/impl/KindOfProductServiceImpl.java
> +        return new ResponseEntityDto<>("Kind of product was successfully deleted", kindOfProduct);
При удалении не нужно возвращать удаленный объект - это бессмысленно, достаточен просто сам факт успешного удаления.

2019-07-25 08:23 UTC, merged